#!/opt/local/bin/perl -w

use strict;
use lib "/home/pi/perl5/lib/perl5";
use RRD::Simple;

# MPV / relay settle time and de-bounce
my $settle = 5;
my $heartbeat = 60;

# The WiringPi GPIO pins we are monitoring
#pin 0 = white wire, pin 2 = grey wire
my %pins = ( 0 => '',
	     2 => '');
# MPV signals => GPIO pin levels (%pins)
#             => Y Plan state bitmap (%yplan)
#my %yplan = (0 => "N:0:1",
#	      2 => "N:1:1",
#	      3 => "N:1:0", );
my %child;
my $rrd = RRD::Simple->new( file => "/home/pi/yplan_status/mpv.rrd" );

# Child routine
sub spawn_child {
	my $pin = $_[0];
	my $pid = fork();
	die unless defined $pid;
	if ($pid == 0) {
		# In the child
		my $ret = system("gpio wfi $pin both");
		sleep $settle unless $ret;
		exit($ret);
	}
	$child{$pid} = $pin;
	msg("   PID +$pid handling wire $pin");
}

# assess pin state
sub update_pin_state {
	my $change = 0;
	
	# an edge event has occurred on at least one pin
	# read both pins
	foreach my $pin (keys %pins) {
		my $level = `gpio read $pin`;
		chomp($level);
		if ($pins{$pin} != $level) {
			$change += 1;
			$pins{$pin} = $level;
			msg("   wire $pin status change -> ". wire($pin));
		}
	}
	return($change);
}

# log something
sub msg {
	local $| = 1;
	print STDOUT localtime() . ": ". $_[0] . "\n";
}

# invert the pin status to represent wire status
sub wire {
	my $wire_state = $pins{$_[0]} == 0 ? 1 : 0;
	return($wire_state);
}

sub update_rrd {	
	my $verbose = $_[0];
#	my $idx = $pins{2} + $pins{3} << 1;
#	return unless exists($yplan{$idx});
#	system($cmd . $yplan{$idx});
	my ($white, $grey) = (wire(0), wire(2));
	$rrd->update(white => $white, grey => $grey);
	msg("wire status = ". $white . ":" . $grey) if ($verbose);
	# restart the timer
	alarm($heartbeat);
}

sub reap {
	alarm(0);
	msg("reaping...");
	kill 'TERM', (keys %child);
	exit 0;
}

# Initialise pin edge change detection
msg("Initialising GPIO pins");
foreach my $pin (keys %pins) {
	# init pin_status
	system("gpio mode $pin in");
	system("gpio mode $pin up");
	$pins{$pin} = `gpio read $pin`;
	chomp($pins{$pin});
	msg("wire $pin status = ". wire($pin));
	spawn_child($pin);
}

# Update status at least every $heartbeat seconds
$SIG{ALRM} = \&update_rrd(0);
update_rrd(1);
$SIG{TERM} = \&reap;

while (1) {
	my $pid = wait();
	# a child has exited
	exists($child{$pid}) or die "Unknown child exited: $pid";
	if ($? == 0) {
		msg("   PID -$pid handling wire ". $child{$pid});
		update_rrd(1) unless (update_pin_state() == 0);
		# replace terminated handler
		spawn_child($child{$pid});
		delete($child{$pid});
	} else {
 		msg("Child $pid died with returncode: $?");
	}
}
